apiVersion: v1
kind: Secret
metadata:
  name: lab-k8s-tls-secret
  namespace: lab-crypto
type: kubernetes.io/tls
data:
  tls.crt: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURkekNDQWx1Z0F3SUJBZ0lVTnljMlRNSG51
    bW5EWTNxQ1Q3Z1JCSnhHSmhzd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1NURUxNQWtHQTFVRUJoTUNW
    Vk14Q3pBSkJnTlZCQUdNQWtkRE1SRXdHd1lDVlFRRERCUlNTV0poY21GaApJRkp2YjNRZ1ExRXhD
    ekFKQmdOVkJBb01BbEZEUFRFaU1DQUdBMTFVRUF3d1pTV0poY21GaElGQnZjM1FnUWpFeQpNREFl
    RjEwME1EQXdNREF3TURBd01EQWFGMTB4TURBd01EQXdNREF3TURBd01EQXdTVExNQWtHQTFVRUJo
    TUNWVk14CkN6QUpCZ05WQkFHTUFrZERNUkV3R3dZQ1ZRUUREQlJTU1dKaGNtRmhJRkp2YjNRZ1Ex
    RXhDekFKQmdOVkJBb00KQWxGRFBURWlNQ0FHQTExVUVBd3daU1dKaGNtRmhJRkJ2YzNRZ1FqRXlN
    SUlCSWpBTkJna3Foa2lHOXcwQkFRRUYKQUFPQ0FROEFNSUlCQ2dLQ0FRRUF3ZlQ1VURmNlEycnhD
    K2tYMmQwc3NkWlBvdTVoVkY3QTVpTFVjRWRiTkdZcApkQXZlQUZJdWtzc2d1VGpzOUw1K0k3TXZN
    OW9hMmdsL3NSRjJrcmFndlVrdmpHMWFvQndnd3k4VkI2aXlCZDlhCmpmOG13c1c4VTZIdmNndmQ2
    a043cWJwbHgySGtsbzU0YlU0VlBldTFRbmw5OWt1TndnckpQOTh0dDFJcjlhUkwKbFhnb3hEaTNu
    T05lRmdDcmFjMEFwQjlhWkJldTFXUkoxVzZzRW4xdk4wUG4xVXZZcndFTHdMTE1KQUd6WkV0NApu
    c3d6OEh3UFNqamdrQ20zaW02Y1lRSEl6WjlEem4wcTlhOGF5cm1lYlI3NGI2NWZWV1hDdzVrdE04
    a1N1NG4yCklNTHI5bEtrME96WHRGZ284bEhyL2drSEd4SjkyU2d0MnpJUXdXSURBUUFBT2pFcz1D
    Zz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.key: |
    LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2Z0lCQURBTkJna3Foa2lHOXcwQkFRRUZB
    QVNDQktnd2dnU2tBZ0VBQW9JQkFRREF3ZlQ1VURmNlEycngKQytrWDJkMHNzZFpQb3U1aFZGN0E1
    aUxVY0VkYk5HWXBkQXZlQUZJdWtzc2d1VGpzOUw1K0k3TXZNOS1SRjJrCg==
