worker_processes 1;
events { worker_connections 1024; }

http {
    default_type application/octet-stream;
    sendfile on;

    server {
        listen 4433 ssl;
        server_name lab-pqc-tls.local localhost;

        ssl_certificate /opt/nginx/certs/lab_cert.pem;
        ssl_certificate_key /opt/nginx/certs/lab_cert.key;

        ssl_protocols TLSv1.3;
        ssl_ecdh_curve kyber768:mlkem768;

        location / {
            return 200 'PQC ML-KEM-768 TLS Active\n';
            add_header Content-Type text/plain;
        }
    }
}
