server {
    listen 8443 ssl;
    server_name lab-classical-tls.local localhost;

    ssl_certificate /etc/nginx/certs/lab_cert.pem;
    ssl_certificate_key /etc/nginx/certs/lab_cert.key;

    ssl_protocols TLSv1.3;
    ssl_ciphers ECDHE-RSA-AES256-GCM-SHA384:TLS_AES_256_GCM_SHA384;
    ssl_prefer_server_ciphers on;

    location / {
        return 200 'Classical TLS 1.3 Active';
        add_header Content-Type text/plain;
    }
}
