server {
    listen 8445 ssl;
    server_name lab-legacy-tls.local localhost;

    ssl_certificate /etc/nginx/certs/lab_cert.pem;
    ssl_certificate_key /etc/nginx/certs/lab_cert.key;

    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers AES128-SHA:DES-CBC3-SHA;
    ssl_prefer_server_ciphers on;

    location / {
        return 200 'Legacy TLS Active';
        add_header Content-Type text/plain;
    }
}
