from enum import Enum

class CryptographicPurpose(str, Enum):
    KEY_ESTABLISHMENT = "KEY_ESTABLISHMENT"
    PUBLIC_KEY_ENCRYPTION = "PUBLIC_KEY_ENCRYPTION"
    DIGITAL_SIGNATURE = "DIGITAL_SIGNATURE"
    CERTIFICATE_SIGNATURE = "CERTIFICATE_SIGNATURE"
    CODE_SIGNING = "CODE_SIGNING"
    IDENTITY_AUTHENTICATION = "IDENTITY_AUTHENTICATION"
    SYMMETRIC_ENCRYPTION = "SYMMETRIC_ENCRYPTION"
    STORAGE_ENCRYPTION = "STORAGE_ENCRYPTION"
    HASH = "HASH"
    MAC = "MAC"
    UNKNOWN = "UNKNOWN"

class PrimitiveQuantumStatus(str, Enum):
    QUANTUM_VULNERABLE = "QUANTUM_VULNERABLE"
    QUANTUM_RESISTANT = "QUANTUM_RESISTANT"
    HYBRID = "HYBRID"
    NOT_APPLICABLE = "NOT_APPLICABLE"
    UNKNOWN = "UNKNOWN"

class AssetReadinessResult(str, Enum):
    READY = "READY"
    PARTIALLY_READY = "PARTIALLY_READY"
    NOT_READY = "NOT_READY"
    INCOMPLETE_COVERAGE = "INCOMPLETE_COVERAGE"
    UNKNOWN = "UNKNOWN"
    NOT_ASSESSED = "NOT_ASSESSED"  # No cryptographic evidence collected for this asset

